name: Block PR with Prerelease label
on:
  pull_request:
    branches: [main]
    types: [labeled, unlabeled, opened, synchronize]
jobs:
  verify-prerelease-version:
    if: contains(github.event.pull_request.labels.*.name, 'prerelease')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            core.setFailed(`PR with a prerelease label cannot be merged. Remove the label or change it to a release label and adjust the version as needed to fix.`)
