name: Check PR version is unchanged
on:
  pull_request:
    branches: [main]
    types: [labeled, unlabeled, opened, synchronize]
jobs:
  verify-version:
    if: "!contains(github.event.pull_request.labels.*.name, 'release') && !contains(github.event.pull_request.labels.*.name, 'prerelease')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Pull Request Version
        id: pr-version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Get Base Version
        id: base-version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn add semver
      - uses: actions/github-script@v6
        env:
          PR_VERSION: ${{steps.pr-version.outputs.version}}
          BASE_VERSION: ${{steps.base-version.outputs.version}}
        with:
          script: |
            const { PR_VERSION: pr, BASE_VERSION: base } = process.env
            if (pr.trim() === base.trim()) {
              core.debug(`Success, the pr version (${pr}) is the same as the base version (${base}).`)
            } else {
              core.setFailed(`The pr version (${pr}) is not the same as the base version (${base}). A pull request without a 'release' or 'prerelease' label cannot include a version bump.`)
            }
