name: Verify Version
on:
  pull_request:
    branches: [main]
    types: [labeled, unlabeled, opened, synchronize]
jobs:
  verify-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: martinbeentjes/npm-get-version-action@main
        id: main-version
      - uses: actions/checkout@v3
      - uses: martinbeentjes/npm-get-version-action@main
        id: pr-version
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn add semver
      - uses: actions/github-script@v6
        env:
          PR_VERSION: ${{steps.pr-version.outputs.current-version}}
          MAIN_VERSION: ${{steps.main-version.outputs.current-version}}
        with:
          script: |
            require('./.github/versioning.js').verify({ github, context, core })
  block-prerelease:
    if: contains(github.event.pull_request.labels.*.name, 'prerelease')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            core.setFailed(`PR with a prerelease label cannot be merged. Remove the label or change it to a release label and adjust the version as needed to fix.`)
